/**
 * Is what an SSH host holds of our agent tools — the canvas and context shims, their SKILL.md files
 * (system and managed-account), and our marker blocks in the codex/gemini/copilot/opencode
 * instruction files — still exactly what this app build would write? And when may we ask?
 *
 * WHY THIS EXISTS. Those files are generated by the app and written onto the host only from the
 * connect path. Nothing ever looked at them again, so a host could keep another build's text for a
 * whole app run: an install that failed open on connect (they are fire-and-forget) was never
 * retried; a tunnel that failed verification at connect and was repaired later on the reuse branch
 * never got them at all; a managed account's skill was written once, when the account was ADDED,
 * and never again — so after an update every remote account session read the verb docs of the
 * build that created the account. And a second desktop sharing the host account writes its own
 * version on its own connects. Agents then read verb docs for a product that no longer exists.
 *
 * THE STAMP IS THE BYTES. The host checksums the files it actually holds (for an instruction file,
 * exactly the span `mergeCanvasControlBlock` / `mergeInstructionsBlock` would replace), and we
 * compare against the checksum of the exact bytes we would write. Nothing is embedded in the
 * artifacts: a stamp line would be noise in every agent's context, would need a migration for
 * hosts written by older builds, and would trust a file's claim about itself — a hand edit or a
 * foreign writer that keeps the line goes unseen. Hashing the bytes catches a generator change
 * with no version bump, a deletion, and a foreign or older writer, and works on day one against
 * files older builds wrote. The checksum is POSIX `cksum` (see posix-cksum.ts for why not sha256);
 * on a host without one, the files it can read are written without comparison (what every connect
 * did before) and the blocks merged — but missing, unreadable and gated files are still told apart.
 *
 * ONE ROUND TRIP. Every file is probed by one generated command whose reply is a few hundred bytes,
 * so a check costs no more than the tunnel probe beside it — and a host that is current costs no
 * write at all.
 */
import { parseCksumLine, type Cksum } from '../../core/remote-ssh/posix-cksum'
import { posixQuote } from '../../shared/ssh'
import { recordTunnelRepair, shouldAttemptTunnelRepair } from './tunnel-repair'

/** One file the probe looks at. `pathExpr` is a ready-to-splice shell word: a `posixQuote`d
 *  literal, or a double-quoted expansion bound through the command's prelude (see
 *  `openCodeInstructionsTarget`). */
export type ProbeEntry =
  | {
      kind: 'file'
      pathExpr: string
      /** A directory that must ALREADY exist for this file to be ours to write — a managed
       *  account's config dir. Absent ⇒ `no-gate`, and the file is never recreated (that would
       *  resurrect the directory of an account the host no longer has). */
      gateDirExpr?: string
    }
  | { kind: 'block'; pathExpr: string; start: string; end: string }

export type ProbeStatus =
  | { state: 'present'; sum: Cksum }
  | { state: 'missing' }
  /** Exists but is not a readable regular file (a directory, a dangling link, no permission).
   *  NEVER written over: we cannot see what we would be replacing. */
  | { state: 'unreadable' }
  | { state: 'no-gate' }
  /** A readable regular file whose content could not be checksummed: the host has no `cksum`, or
   *  awk failed on this instruction file. Not evidence either way — the caller writes an owned file
   *  (what every connect did before the check) and MERGES an instruction block, which writes only
   *  when the merge changes something. */
  | { state: 'unknown' }

export interface AgentToolsReport {
  /** False on a host with no `cksum`: every readable file is then `unknown`. */
  hasCksum: boolean
  statuses: ProbeStatus[]
  env: string
}

const HEADER = 'NT_AGENT_TOOLS_CHECK 1'
const END = 'NT_END'

/**
 * The span of an instruction file that `merge*Block` would replace, printed byte for byte (awk
 * under LC_ALL=C, so `index`/`substr` count bytes): from the FIRST start marker through the end of
 * the first end marker AFTER it — the merge's own rule, so a stray end line left above a
 * hand-deleted block is skipped here exactly as it is there. No start marker, or none of the end
 * marker after it, is no block: nothing is printed and the merge appends. Lines are rejoined with
 * the `\n` awk split them on; a `\r` stays inside its line, so a CRLF file does not pass for our
 * LF block.
 */
const AWK_BLOCK =
  '{ t = (NR == 1) ? $0 : t "\\n" $0 } ' +
  'END { i = index(t, s); if (i > 0) { r = substr(t, i); j = index(r, e); ' +
  'if (j > 0) printf "%s", substr(r, 1, j - 1 + length(e)) } }'

/**
 * The probe. Output, one line each: the header; `NT_NO_CKSUM` when the host has no `cksum`; one
 * status per entry, in order (`<i> C <crc> <size>` | `<i> M` | `<i> U` | `<i> D` | `<i> X`); then
 * `NT_ENV <name>=<value>` (the one environment variable the caller needs resolved on the host —
 * printed LAST, because it is host data and must not be able to forge a status line); then `NT_END`.
 *
 * Missing / unreadable / gate are decided for every entry even without `cksum`: those are the
 * refusals, and a host without a checksum tool must not lose them. An awk that fails on a block is
 * reported as `X` through fd 3 rather than hidden behind the pipeline, whose status is `cksum`'s.
 */
export function agentToolsCheckCommand(prelude: string, entries: readonly ProbeEntry[], envName: string): string {
  if (!/^[A-Z_][A-Z0-9_]*$/.test(envName)) throw new Error(`not an environment variable name: ${envName}`)
  for (const e of entries) {
    // awk -v expands backslash escapes; our markers have none, and a future one must not slip in.
    if (e.kind === 'block' && (e.start.includes('\\') || e.end.includes('\\'))) {
      throw new Error('a block marker may not contain a backslash')
    }
  }
  const fns =
    `nt_s() { if [ ! -e "$2" ] && [ ! -L "$2" ]; then printf '%s M\\n' "$1"; return 1; fi; ` +
    `if [ ! -f "$2" ] || [ ! -r "$2" ]; then printf '%s U\\n' "$1"; return 1; fi; ` +
    `[ -n "$nt_k" ] && return 0; printf '%s X\\n' "$1"; return 1; }; ` +
    `nt_f() { nt_s "$1" "$2" || return 0; nt_c=$(cksum < "$2") || { printf '%s U\\n' "$1"; return 0; }; ` +
    `printf '%s C %s\\n' "$1" "$nt_c"; }; ` +
    `nt_g() { if [ -d "$3" ]; then nt_f "$1" "$2"; else printf '%s D\\n' "$1"; fi; }; ` +
    `nt_b() { nt_s "$1" "$2" || return 0; ` +
    `nt_c=$( { { awk -v s="$3" -v e="$4" ${posixQuote(AWK_BLOCK)} "$2" || printf '%s\\n' NT_AWK_FAILED >&3; } | cksum; } 3>&1 ) || ` +
    `{ printf '%s U\\n' "$1"; return 0; }; ` +
    `case "$nt_c" in *NT_AWK_FAILED*) printf '%s X\\n' "$1" ;; *) printf '%s C %s\\n' "$1" "$nt_c" ;; esac; }; `
  const probes = entries
    .map((e, i) => {
      if (e.kind === 'block') return `nt_b ${i} ${e.pathExpr} ${posixQuote(e.start)} ${posixQuote(e.end)}; `
      return e.gateDirExpr ? `nt_g ${i} ${e.pathExpr} ${e.gateDirExpr}; ` : `nt_f ${i} ${e.pathExpr}; `
    })
    .join('')
  const env = `printf 'NT_ENV %s=%s\\n' ${envName} "\${${envName}:-}"; printf '%s\\n' ${END}`
  return (
    `${prelude}LC_ALL=C; export LC_ALL; printf '%s\\n' ${posixQuote(HEADER)}; ` +
    `nt_k=; if command -v cksum >/dev/null 2>&1; then nt_k=1; else printf '%s\\n' NT_NO_CKSUM; fi; ` +
    `${fns}${probes}${env}`
  )
}

/**
 * Parse the probe's reply. Anything that is not exactly the shape above is `null` — a report we
 * cannot read is never evidence that a file is stale (or current); the caller retries later. A
 * login banner printed before the header is tolerated.
 */
export function parseAgentToolsReport(stdout: string, count: number): AgentToolsReport | null {
  const at = stdout.indexOf(`${HEADER}\n`)
  if (at < 0) return null
  const body = stdout.slice(at + HEADER.length + 1)
  const envAt = body.indexOf('NT_ENV ')
  if (envAt < 0 || (envAt > 0 && body[envAt - 1] !== '\n')) return null
  const tail = body.slice(envAt)
  const endAt = tail.lastIndexOf(`\n${END}`)
  if (endAt < 0 || tail.slice(endAt).trim() !== END) return null
  const eq = tail.indexOf('=')
  if (eq < 0 || eq > endAt) return null
  const env = tail.slice(eq + 1, endAt)
  const lines = body.slice(0, envAt).split('\n').filter((l, i, all) => !(i === all.length - 1 && l === ''))
  const hasCksum = lines[0] !== 'NT_NO_CKSUM'
  if (!hasCksum) lines.shift()
  if (lines.length !== count) return null
  const statuses: ProbeStatus[] = []
  for (let i = 0; i < count; i++) {
    const m = /^(\d+) (C (.+)|M|U|D|X)$/.exec(lines[i])
    if (!m || Number(m[1]) !== i) return null
    if (m[2] === 'M') statuses.push({ state: 'missing' })
    else if (m[2] === 'U') statuses.push({ state: 'unreadable' })
    else if (m[2] === 'D') statuses.push({ state: 'no-gate' })
    else if (m[2] === 'X') statuses.push({ state: 'unknown' })
    else {
      // A host that said it has no cksum cannot have produced a checksum.
      const sum = hasCksum ? parseCksumLine(m[3]) : null
      if (!sum) return null
      statuses.push({ state: 'present', sum })
    }
  }
  return { hasCksum, statuses, env }
}

// ---- cadence --------------------------------------------------------------------------------

/**
 * How long a confirmed host goes before the reuse branch looks again. Within one app run our own
 * bytes cannot change, so the only thing a re-look can find is a writer outside this run — another
 * desktop (possibly another build) on the same host account, or a hand edit. Hourly bounds how long
 * that lasts at one read per host per hour, and bounds a two-desktop tug-of-war to one write each.
 */
export const AGENT_TOOLS_RECHECK_MS = 60 * 60_000

/** What woke the check. `connect` = a master was just (re-)established, `repair` = the reuse
 *  branch just rebuilt a dead hook tunnel, `reuse` = a routine connect() on a live master (the 45 s
 *  watchdog, a tab switch). */
export type AgentToolsTrigger = 'connect' | 'repair' | 'reuse'

export interface AgentToolsHostState {
  /** The expected set the last SUCCESSFUL check confirmed, and when. */
  verified?: { setId: string; at: number }
  /** Consecutive failed checks since the last success (the same backoff shape as tunnel repair). */
  failures: number
  lastAttemptAt: number
}

/**
 * May we check this host now?
 *
 * A connect or a repair always may: a master just came up, it is rare, and it is exactly when the
 * host could have been touched by someone else. The reuse branch runs every 45 s per project, so
 * there it costs NOTHING once this run has confirmed the host for the set we would write — until
 * the hourly re-look. An unconfirmed host (the connect-time check failed, or never ran because the
 * tunnel was not verified then) is retried on the reuse branch with the tunnel-repair backoff:
 * immediately, then 1 / 5 / 15 minutes — a host whose files cannot be written is not rewritten
 * every tick.
 */
export function agentToolsCheckDue(
  state: AgentToolsHostState | undefined,
  setId: string,
  now: number,
  trigger: AgentToolsTrigger
): boolean {
  if (trigger !== 'reuse') return true
  const v = state?.verified
  if (v && v.setId === setId && now - v.at < AGENT_TOOLS_RECHECK_MS) return false
  return shouldAttemptTunnelRepair(state, now)
}

/** Fold one check's outcome into the state `agentToolsCheckDue` reads. A failure keeps the earlier
 *  confirmation (it still describes the last known-good set) but counts toward the backoff. */
export function recordAgentToolsCheck(
  state: AgentToolsHostState | undefined,
  setId: string,
  ok: boolean,
  now: number
): AgentToolsHostState {
  const next = recordTunnelRepair(state, ok, now)
  return { ...next, verified: ok ? { setId, at: now } : state?.verified }
}
