// Renders the Termscape app icon into build/icon.png (1024x1024, the Linux icon), the
// multi-resolution build/icon.ico used by Windows packaging, and the multi-resolution
// build/icon.icns used by macOS packaging (all gitignored — regenerated by `npm run
// make-icon`, which every dist script runs first). electron-builder embeds the ICNS and
// ICO as-is; deriving the .icns from the PNG is exactly what shipped issue #369.
//
// Design: the Termscape mark shared with the iOS companion (resources/brand/termscape-appicon.svg,
// copied from nodeterm-mobile design/AppIcon.svg): two overlapping terminal panes with a purple
// `>_` prompt on a near-black ground. Deliberately NOT upstream's node-graph mark: BUSL-1.1
// grants no rights in the Licensor's logo, so this fork ships its own.
import { mkdirSync, readFileSync, writeFileSync } from 'fs'
import sharp from 'sharp'
import { ICNS_FRAMES, packIcns } from './icon-pack.mjs'

// The full-bleed 1024² Termscape icon (same vector the iOS companion ships; see the provenance
// note inside the file). macOS app icons leave a transparent margin around a rounded-square tile
// so they sit at the same visual size as system icons in the Dock. Apple's grid puts the tile at
// ~824px inside the 1024 canvas (≈100px margin) with a ~185px corner radius. iOS masks its own
// corners, so the source is a plain square: nest it as an inner <svg> scaled into the tile and
// clip it to the tile's rounded rect. The inner document keeps its own <defs>; the only outer id
// is the clip path, so nothing collides.
const source = readFileSync(new URL('../resources/brand/termscape-appicon.svg', import.meta.url), 'utf8')
  .replace(/<!--[\s\S]*?-->/g, '') // the provenance comment
  .replace(/<svg\b[^>]*>/, '<svg x="100" y="100" width="824" height="824" viewBox="0 0 1024 1024">')
if (!source.includes('<svg x="100"')) throw new Error('termscape-appicon.svg: root <svg> not found')
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <defs>
    <clipPath id="tile"><rect x="100" y="100" width="824" height="824" rx="185"/></clipPath>
  </defs>
  <g clip-path="url(#tile)">${source}</g>
  <rect x="101" y="101" width="822" height="822" rx="184" fill="none"
        stroke="#ffffff" stroke-opacity="0.07" stroke-width="2"/>
</svg>`

mkdirSync('build', { recursive: true })
const png = await sharp(Buffer.from(svg)).png().toBuffer()
writeFileSync('build/icon.png', png)
console.log('wrote build/icon.png (1024x1024)')

// --- Windows .ico (multi-resolution) ---
//
// electron-builder's `win.icon` expects a real ICO container, not a PNG wearing a `.ico`
// extension — Explorer, the taskbar and "Programs and Features" each pick a frame by SIZE,
// and a single-frame file gets stretched/blurred everywhere but the one size it matches.
// NSIS additionally requires a 256px frame to be present.
//
// Windows Vista+ accepts PNG-compressed frames packed directly inside an ICO container (no
// BMP/DIB re-encoding required), so this renders the same SVG at each standard size and
// writes a small hand-rolled ICO container around the PNGs — no extra npm dependency for
// something this documented (MS-ICO: a 6-byte ICONDIR header, then one 16-byte ICONDIRENTRY
// per frame, then the frame bytes back to back).
const ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]

/** Pack PNG buffers (one per size, same order as `sizes`) into a Windows ICO file buffer. */
function packIco(sizes, pngBuffers) {
  const HEADER_BYTES = 6
  const ENTRY_BYTES = 16
  const dir = Buffer.alloc(HEADER_BYTES)
  dir.writeUInt16LE(0, 0) // reserved, must be 0
  dir.writeUInt16LE(1, 2) // image type: 1 = icon
  dir.writeUInt16LE(sizes.length, 4) // frame count

  const entries = []
  let offset = HEADER_BYTES + ENTRY_BYTES * sizes.length
  for (let i = 0; i < sizes.length; i++) {
    const size = sizes[i]
    const data = pngBuffers[i]
    const entry = Buffer.alloc(ENTRY_BYTES)
    // Width/height are single bytes; the ICO format's documented escape is 0 == 256px.
    entry.writeUInt8(size >= 256 ? 0 : size, 0)
    entry.writeUInt8(size >= 256 ? 0 : size, 1)
    entry.writeUInt8(0, 2) // color count: 0 = no palette (true color)
    entry.writeUInt8(0, 3) // reserved, must be 0
    entry.writeUInt16LE(1, 4) // color planes
    entry.writeUInt16LE(32, 6) // bits per pixel (32 = RGBA)
    entry.writeUInt32LE(data.length, 8) // size of this frame's data
    entry.writeUInt32LE(offset, 12) // offset of this frame's data from file start
    entries.push(entry)
    offset += data.length
  }
  return Buffer.concat([dir, ...entries, ...pngBuffers])
}

const icoFrames = await Promise.all(
  ICO_SIZES.map((size) => sharp(Buffer.from(svg)).resize(size, size).png().toBuffer())
)
writeFileSync('build/icon.ico', packIco(ICO_SIZES, icoFrames))
console.log(`wrote build/icon.ico (${ICO_SIZES.join('/')}px frames)`)

// --- macOS .icns (multi-resolution) ---
//
// Packed by hand since issue #369: deriving the .icns from icon.png let electron-builder's
// converter ship wrong-sized payloads (the 512px frame in ic13's 256px slot, 1024px in
// ic14's 512px one), which macOS's app launcher painted as rainbow noise. packIcns
// (scripts/icon-pack.mjs, pinned by src/main/icon-pack.test.ts) refuses any frame whose
// dimensions disagree with its type, so that skew now fails the build instead of shipping.
// package.json's mac.icon points at this file; electron-builder embeds it as-is.
const icnsFrames = new Map(
  await Promise.all(
    ICNS_FRAMES.map(async ({ type, px }) => [
      type,
      await sharp(Buffer.from(svg)).resize(px, px).png().toBuffer()
    ])
  )
)
writeFileSync('build/icon.icns', packIcns(icnsFrames))
console.log(`wrote build/icon.icns (${ICNS_FRAMES.map((f) => `${f.type}=${f.px}`).join(' ')})`)
